import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import { LoginButton, LogoutButton } from './auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar bg-base-300">
        <a className="btn btn-ghost normal-case text-xl">daisyUI</a>
        <div className="navbar-end">
          <LoginButton/>
          <LogoutButton/>
        </div>
      </div>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
